cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'fasd'
brew 'ffmpeg'
# brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'jsonpp'
brew 'libgit2'
# brew 'openssl'
brew 'readline'
brew 'postgresql'
# brew 'python'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'yt-dlp'

# cask '1password'
# cask 'adium'
# cask 'atom'
# cask 'caffeine'
# cask 'controlplane'
# cask 'coderunner'
# cask 'dropbox'
# cask 'emacs'
# cask 'firefox'
# cask 'google-chrome'
# cask 'licecap'
# cask 'handbrake'
# cask 'hazel'
# cask 'houdahspot'
# cask 'iterm2'
# cask 'nvalt'
# cask 'vagrant'
# cask 'vlc'
# cask 'virtualbox'
# cask 'vlc'